### ISSUE TITLE
DNS Resolver (Unbound) not working for me

### ISSUE THREAD

**Issue by trevor-crowley** [marshallford/terraform-provider-pfsense#5]
This is an excellent project.   I got all the exmaples to work except for the this one.   terraform says the plan works but I cannot see the results in the GUI or the config file.   Is there a trick to viewing this?

**Comment by marshallford** [comment]
Did you add `include-toplevel: /var/unbound/conf.d/*` to the DNS Resolver custom options input? The `pfsense_dnsresolver_configfile` resource simply writes files to that file path and upon apply Unbound includes the contents as a part of the main config.

**Comment by trevor-crowley** [comment]
Sorry, I should have read your docs more closely.  Tried many times with your v0.3 and no dice.   ff success but no resources to see.

pfSense = Current Base System2.7.0

I then upgraded to your v0.4 and getting some error messages around this:
INPUT:
  pfsense_dnsresolver_configfile.example will be created
  + resource "pfsense_dnsresolver_configfile" "example" {
      + apply   = true
      + content = <<-EOT
            server:
            local-zone: "subdomain.example.com" redirect
            local-data: "subdomain.example.com 3600 IN A 10.10.10.10"
        EOT
      + name    = "wildcard-record-example"
    }
OUTPUT:
Error: Error creating config file
│ 
│   with pfsense_dnsresolver_configfile.example,
│   on main.tf line 66, in resource "pfsense_dnsresolver_configfile" "example":
│   66: resource "pfsense_dnsresolver_configfile" "example" {
│ 
│ unexpected error: failed to create config file, unable to parse config file
│ response, client validation, config file name must only consist of lowercase
│ alphanumeric characters (with dashes)

**Comment by marshallford** [comment]
Hmmm... `state rm` the resource and try again. I have not documented this, but any release below v1.0.0 is considered breaking. Assuming you are able to then get the resource to create/update, you can test your change by running the command `nslookup one.two.three.subdomain.example.com` with an expected response of `10.10.10.10`.

**Comment by marshallford** [comment]
I should also bit more clear in the docs for this resource, but you will not see this config file appear in the DNS resolver UI. The only way to validate your change via the UI is by using the [edit file](https://docs.netgate.com/pfsense/en/latest/diagnostics/edit-file.html) tool to view the file `/var/unbound/conf.d/wildcard-record-example.conf`.

**Comment by trevor-crowley** [comment]
Magic!  thank you.   

nslookup one.two.three.subdomain.example.com
Server:		192.168.88.1
Address:	192.168.88.1#53
Name:	one.two.three.subdomain.example.com
Address: 10.10.10.10
